import * as bip39 from 'bip39';
import { ethers } from 'ethers';
import nacl from 'tweetnacl';
import { encodeBase64, decodeBase64 } from 'tweetnacl-util';
import { Buffer } from 'buffer';

// Make Buffer globally available for browser compatibility
if (typeof window !== 'undefined' && !(window as Window & typeof globalThis & { Buffer?: typeof Buffer }).Buffer) {
  (window as Window & typeof globalThis & { Buffer: typeof Buffer }).Buffer = Buffer;
}

/**
 * Generates a new 12-word mnemonic seed phrase
 */
export function generateSeedPhrase(): string {
  return bip39.generateMnemonic(128); // 128 bits = 12 words
}

/**
 * Validates a seed phrase
 */
export function validateSeedPhrase(seedPhrase: string): boolean {
  return bip39.validateMnemonic(seedPhrase);
}

/**
 * Derives a keypair from seed phrase
 */
export function deriveKeypair(seedPhrase: string): nacl.BoxKeyPair {
  if (!validateSeedPhrase(seedPhrase)) {
    throw new Error('Invalid seed phrase');
  }
  
  const seed = bip39.mnemonicToSeedSync(seedPhrase);
  // Use first 32 bytes of seed for ed25519 keypair
  const privateKey = seed.slice(0, 32);
  return nacl.box.keyPair.fromSecretKey(privateKey);
}

/**
 * Derives auth token from seed phrase using PBKDF2
 * This matches the backend implementation for authentication
 */
export async function deriveAuthToken(seedPhrase: string): Promise<string> {
  const encoder = new TextEncoder();
  const salt = 'sphyre-wallet-v1';
  const iterations = 100000;
  
  // Import the seed phrase as key material
  const keyMaterial = await crypto.subtle.importKey(
    'raw',
    encoder.encode(seedPhrase),
    { name: 'PBKDF2' },
    false,
    ['deriveBits']
  );
  
  // Derive bits using PBKDF2
  const derivedBits = await crypto.subtle.deriveBits(
    {
      name: 'PBKDF2',
      salt: encoder.encode(salt),
      iterations: iterations,
      hash: 'SHA-256',
    },
    keyMaterial,
    256 // 32 bytes = 256 bits
  );
  
  // Convert to hex string
  const hashArray = Array.from(new Uint8Array(derivedBits));
  const hashHex = hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
  
  return hashHex;
}

/**
 * DEPRECATED - DID is now generated by backend
 * Kept for backward compatibility only
 * @deprecated Use backend-generated DID instead
 */
export function generateDID(seedPhrase: string): string {
  console.warn('generateDID is deprecated. DID should be generated by backend.');
  const keypair = deriveKeypair(seedPhrase);
  // Create a base64 encoded identifier from public key
  const identifier = encodeBase64(keypair.publicKey)
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=/g, '');
  
  return `did:alyra:${identifier}`;
}

/**
 * Derives an Ethereum-compatible wallet from seed phrase
 * This can be used for blockchain interactions if needed
 */
export function deriveEthereumWallet(seedPhrase: string): ethers.HDNodeWallet {
  if (!validateSeedPhrase(seedPhrase)) {
    throw new Error('Invalid seed phrase');
  }
  
  return ethers.HDNodeWallet.fromPhrase(seedPhrase);
}

/**
 * Gets the Ethereum address from seed phrase
 */
export function getEthereumAddress(seedPhrase: string): string {
  const wallet = deriveEthereumWallet(seedPhrase);
  return wallet.address;
}

/**
 * Encrypts data using a password (for secure storage)
 */
export function encryptData(data: string, password: string): string {
  const salt = nacl.randomBytes(nacl.secretbox.nonceLength);
  const key = nacl.hash(new TextEncoder().encode(password + salt.toString())).slice(0, nacl.secretbox.keyLength);
  const nonce = nacl.randomBytes(nacl.secretbox.nonceLength);
  const message = new TextEncoder().encode(data);
  const encrypted = nacl.secretbox(message, nonce, key);
  
  const fullMessage = new Uint8Array(salt.length + nonce.length + encrypted.length);
  fullMessage.set(salt);
  fullMessage.set(nonce, salt.length);
  fullMessage.set(encrypted, salt.length + nonce.length);
  
  return encodeBase64(fullMessage);
}

/**
 * Decrypts data using a password
 */
export function decryptData(encryptedData: string, password: string): string {
  const fullMessage = decodeBase64(encryptedData);
  const salt = fullMessage.slice(0, nacl.secretbox.nonceLength);
  const nonce = fullMessage.slice(nacl.secretbox.nonceLength, nacl.secretbox.nonceLength * 2);
  const encrypted = fullMessage.slice(nacl.secretbox.nonceLength * 2);
  
  const key = nacl.hash(new TextEncoder().encode(password + salt.toString())).slice(0, nacl.secretbox.keyLength);
  const decrypted = nacl.secretbox.open(encrypted, nonce, key);
  
  if (!decrypted) {
    throw new Error('Decryption failed');
  }
  
  return new TextDecoder().decode(decrypted);
}

/**
 * Signs a message with the private key derived from seed phrase
 */
export function signMessage(message: string, seedPhrase: string): string {
  const keypair = deriveKeypair(seedPhrase);
  const messageBytes = new TextEncoder().encode(message);
  const signature = nacl.sign.detached(messageBytes, keypair.secretKey);
  return encodeBase64(signature);
}

// ====== NEW: Ed25519 helpers for did:key flows ======

/** Derive an Ed25519 signing keypair from seed phrase */
export function deriveSigningKeypair(seedPhrase: string): nacl.SignKeyPair {
  if (!validateSeedPhrase(seedPhrase)) {
    throw new Error('Invalid seed phrase');
  }
  const seed = bip39.mnemonicToSeedSync(seedPhrase);
  const privateSeed = seed.slice(0, 32);
  return nacl.sign.keyPair.fromSeed(privateSeed);
}

/** Base58BTC encoder (no external deps) */
const B58_ALPHABET = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
function base58btcEncode(bytes: Uint8Array): string {
  if (bytes.length === 0) return '';
  // Count leading zeros
  let zeros = 0;
  while (zeros < bytes.length && bytes[zeros] === 0) zeros++;
  // Convert base256 to base58
  const digits: number[] = [0];
  for (let i = zeros; i < bytes.length; i++) {
    let carry = bytes[i];
    for (let j = 0; j < digits.length; j++) {
      carry += digits[j] << 8;
      digits[j] = carry % 58;
      carry = (carry / 58) | 0;
    }
    while (carry > 0) {
      digits.push(carry % 58);
      carry = (carry / 58) | 0;
    }
  }
  // Compose string
  let result = '';
  for (let i = 0; i < zeros; i++) result += '1';
  for (let i = digits.length - 1; i >= 0; i--) result += B58_ALPHABET[digits[i]];
  return result;
}

/** Build did:key (Ed25519) from seed phrase */
export function didKeyFromSeedPhrase(seedPhrase: string): string {
  const kp = deriveSigningKeypair(seedPhrase);
  // multicodec prefix for ed25519-pub is 0xED01
  const prefix = new Uint8Array([0xed, 0x01]);
  const data = new Uint8Array(prefix.length + kp.publicKey.length);
  data.set(prefix, 0);
  data.set(kp.publicKey, prefix.length);
  const multibase = 'z' + base58btcEncode(data);
  return `did:key:${multibase}`;
}

/** Sign message using Ed25519 derived from seed phrase */
export function signMessageEd25519(message: string, seedPhrase: string): string {
  const kp = deriveSigningKeypair(seedPhrase);
  const messageBytes = new TextEncoder().encode(message);
  const signature = nacl.sign.detached(messageBytes, kp.secretKey);
  return encodeBase64(signature);
}

/** Sign a base64-encoded payload using Ed25519 (signs decoded bytes) */
export function signBase64Ed25519(base64Message: string, seedPhrase: string): string {
  const kp = deriveSigningKeypair(seedPhrase);
  const messageBytes = decodeBase64(base64Message);
  const signature = nacl.sign.detached(messageBytes, kp.secretKey);
  return encodeBase64(signature);
}

/**
 * Verifies a signature
 */
export function verifySignature(message: string, signature: string, publicKey: Uint8Array): boolean {
  const messageBytes = new TextEncoder().encode(message);
  const signatureBytes = decodeBase64(signature);
  return nacl.sign.detached.verify(messageBytes, signatureBytes, publicKey);
}

export interface WalletData {
  did: string;
  publicKey: string;
  ethereumAddress: string;
  createdAt: string;
}

/**
 * Generates complete wallet data from seed phrase
 */
export function generateWalletData(seedPhrase: string): WalletData {
  const did = generateDID(seedPhrase);
  const keypair = deriveKeypair(seedPhrase);
  const ethereumAddress = getEthereumAddress(seedPhrase);
  
  return {
    did,
    publicKey: encodeBase64(keypair.publicKey),
    ethereumAddress,
    createdAt: new Date().toISOString()
  };
}
